import { ENV_VARIABLES } from ".";

export default  {
    HOST: ENV_VARIABLES.REPORT_DB_CONFIG.REPORT_DB_HOST,
    PORT: ENV_VARIABLES.REPORT_DB_CONFIG.REPORT_DB_PORT,
    USER: ENV_VARIABLES.REPORT_DB_CONFIG.REPORT_DB_USER,
    PASSWORD: ENV_VARIABLES.REPORT_DB_CONFIG.REPORT_DB_PASSWORD,
    DB: ENV_VARIABLES.REPORT_DB_CONFIG.REPORT_DB_DATABASE,
    dialect: "mssql",
    pool: {
      max: 5,
      min: 0,
      acquire: 30000,
      idle: 10000
    }
  };
